# Make the app show up as cart-podinfo (like before)
nameOverride: cart-podinfo

service:
  enabled: true
  type: NodePort      # <- expose outside the cluster
  httpPort: 9898      # podinfo HTTP port
  grpcPort: 9999      # podinfo gRPC port
  metricsPort: 9797   # Prometheus metrics port

  # Optional: fix the NodePort numbers yourself
  nodePort: 30080         # HTTP
  grpcNodePort: 30081     # gRPC (only if you need it)
  metricsNodePort: 30082  # metrics (usually not needed externally)
